version: "3"
services:
  mysql:
    container_name: finance-mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - code-network
  redis:
    container_name: finance-redis
    image: redis:4.0-alpine
    ports:
      - 6379:6379
    networks:
      - code-network
  web:
    container_name: finance-web
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker/php/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - code-network
  php:
    container_name: finance-php
    build: ./docker/php
    user: "1000"
    expose:
      - 9000
    volumes:
      - ./:/var/www/html
    networks:
      - code-network

  node:
    container_name: finance-node
    image: node
    user: "1000"
    volumes:
      - ./:/var/www/html
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
